routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the 'web' middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('home');
});

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('profile', [App\Http\Controllers\UserController::class, 'showProfile'])->name('user.profile');
    Route::get('user-data', [App\Http\Controllers\UserController::class, 'getDatatables'])->name('user.data');
    Route::patch('profile', [App\Http\Controllers\UserController::class, 'updateProfile'])->name('user.update-profile');
    Route::resource('user', App\Http\Controllers\UserController::class);

    Route::get('purchase-request-data', [App\Http\Controllers\PurchaseRequestController::class, 'getDatatables'])->name('purchase-request.data');
    Route::patch('purchase-request/{purchase_request}/finalize', [App\Http\Controllers\PurchaseRequestController::class, 'finalize'])->name('purchase-request.finalize');
    Route::resource('purchase-request', App\Http\Controllers\PurchaseRequestController::class);

    Route::get('purchase-request/{purchase_request}/quotation/create', [App\Http\Controllers\QuotationController::class, 'create'])->name('purchase-request.create-quotation');
    Route::post('purchase-request/{purchase_request}/quotation/store', [App\Http\Controllers\QuotationController::class, 'store'])->name('purchase-request.store-quotation');
    Route::get('purchase-request/{purchase_request}/quotation/index', [App\Http\Controllers\QuotationController::class, 'index'])->name('purchase-request.index-quotation');
    Route::get('purchase-request/{purchase_request}/quotation/datatable', [App\Http\Controllers\QuotationController::class, 'getDatatables'])->name('purchase-request.datatable-quotation');

    Route::get('quotation/{quotation}', [App\Http\Controllers\QuotationController::class, 'show'])->name('quotation.show');
    Route::get('quotation', [App\Http\Controllers\QuotationController::class, 'index'])->name('quotation.index');
    Route::get('quotation-data', [App\Http\Controllers\QuotationController::class, 'getDatatables'])->name('quotation.data');
    Route::patch('quotation/{quotation}', [App\Http\Controllers\QuotationController::class, 'update'])->name('quotation.update');
    Route::patch('quotation/{quotation}/finalize', [App\Http\Controllers\QuotationController::class, 'finalize'])->name('quotation.finalize');

    Route::get('api-server-data', [App\Http\Controllers\ApiServerController::class, 'getDatatables'])->name('api-server.data');
    Route::resource('api-server', App\Http\Controllers\ApiServerController::class);
});
// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/dashboard.blade.php
@extends('layouts.master')

@section('title') {{ __('Dashboard') }}  @endsection

@section('content')

    @component('components.breadcrumb')
        @slot('li_1') Dashboard @endslot
        @slot('title') Home @endslot
    @endcomponent

    <div class="row">
        <div class="col-xl-4">
            <div class="card overflow-hidden">
                <div class="bg-primary bg-soft">
                    <div class="row">
                        <div class="col-7">
                            <div class="text-primary p-3">
                                <h5 class="text-primary">{{ __('Welcome Back') }}!</h5>
                                <p>RFQ Dashboard</p>
                            </div>
                        </div>
                        <div class="col-5 align-self-end">
                            <img src="{{ URL::asset('/assets/images/profile-img.png') }}" alt="" class="img-fluid">
                        </div>
                    </div>
                </div>
                <div class="card-body pt-0">
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="avatar-md profile-user-wid mb-4">
                                <img src="{{ auth()->user()->avatar_path }}" alt="" class="img-thumbnail rounded-circle dashboard-avatar">
                            </div>
                            <h5 class="font-size-15 text-truncate">{{ Str::ucfirst(auth()->user()->name) }}</h5>
                            <p class="text-muted mb-0 text-truncate">{{ Str::ucfirst(auth()->user()->roles()->first()->name) }}</p>
                        </div>

                        <div class="col-sm-8">
                            <div class="pt-4">

                                <div class="row">
                                    <div class="col-6">
                                        <h5 class="font-size-15">{{ \App\Models\PurchaseRequest::active()->count() }}</h5>
                                        <p class="text-muted mb-0">{{ __('Purchase Requests') }}</p>
                                    </div>
                                    <div class="col-6">
                                        <h5 class="font-size-15">{{ \App\Models\Vendor::active()->count() }}</h5>
                                        <p class="text-muted mb-0">{{ __('Vendors') }}</p>
                                    </div>
                                </div>
                                <div class="mt-4">
                                    <a href="{{ route('home') }}" class="btn btn-primary waves-effect waves-light btn-sm">View Profile <i class="mdi mdi-arrow-right ms-1"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <!-- end row -->

    <!-- Transaction Modal -->
    <div class="modal fade transaction-detailModal" tabindex="-1" role="dialog"
        aria-labelledby="transaction-detailModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="transaction-detailModalLabel">Order Details</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p class="mb-2">Product id: <span class="text-primary">#SK2540</span></p>
                    <p class="mb-4">Billing Name: <span class="text-primary">Neal Matthews</span></p>

                    <div class="table-responsive">
                        <table class="table align-middle table-nowrap">
                            <thead>
                                <tr>
                                    <th scope="col">Product</th>
                                    <th scope="col">Product Name</th>
                                    <th scope="col">Price</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <th scope="row">
                                        <div>
                                            <img src="{{ URL::asset('/assets/images/product/img-7.png') }}" alt="" class="avatar-sm">
                                        </div>
                                    </th>
                                    <td>
                                        <div>
                                            <h5 class="text-truncate font-size-14">Wireless Headphone (Black)</h5>
                                            <p class="text-muted mb-0">$ 225 x 1</p>
                                        </div>
                                    </td>
                                    <td>$ 255</td>
                                </tr>
                                <tr>
                                    <th scope="row">
                                        <div>
                                            <img src="{{ URL::asset('/assets/images/product/img-4.png') }}" alt="" class="avatar-sm">
                                        </div>
                                    </th>
                                    <td>
                                        <div>
                                            <h5 class="text-truncate font-size-14">Phone patterned cases</h5>
                                            <p class="text-muted mb-0">$ 145 x 1</p>
                                        </div>
                                    </td>
                                    <td>$ 145</td>
                                </tr>
                                <tr>
                                    <td colspan="2">
                                        <h6 class="m-0 text-right">Sub Total:</h6>
                                    </td>
                                    <td>
                                        $ 400
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="2">
                                        <h6 class="m-0 text-right">Shipping:</h6>
                                    </td>
                                    <td>
                                        Free
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="2">
                                        <h6 class="m-0 text-right">Total:</h6>
                                    </td>
                                    <td>
                                        $ 400
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    <!-- end modal -->

    <!-- subscribeModal -->
    <div class="modal fade" id="subscribeModal" tabindex="-1" aria-labelledby="subscribeModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header border-bottom-0">
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="text-center mb-4">
                        <div class="avatar-md mx-auto mb-4">
                            <div class="avatar-title bg-light rounded-circle text-primary h1">
                                <i class="mdi mdi-email-open"></i>
                            </div>
                        </div>

                        <div class="row justify-content-center">
                            <div class="col-xl-10">
                                <h4 class="text-primary">Subscribe !</h4>
                                <p class="text-muted font-size-14 mb-4">Subscribe our newletter and get notification to stay
                                    update.</p>

                                <div class="input-group bg-light rounded">
                                    <input type="email" class="form-control bg-transparent border-0"
                                        placeholder="Enter Email address" aria-label="Recipient's username"
                                        aria-describedby="button-addon2">

                                    <button class="btn btn-primary" type="button" id="button-addon2">
                                        <i class="bx bxs-paper-plane"></i>
                                    </button>

                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end modal -->

@endsection
@section('script')
    <!-- apexcharts -->
    <script src="{{ URL::asset('/assets/libs/apexcharts/apexcharts.min.js') }}"></script>

    <!-- dashboard init -->
    <script src="{{ URL::asset('/assets/js/pages/dashboard.init.js') }}"></script>
@endsection

resources/views/datatables.blade.php
<!-- Classes used in public/js/datatables/ext.classes.js -->
<div class="w-1/2 hidden bg-gray-100 content-center clear-both float-left top-2/4 border-l border-r border-t border-b float-right"></div>

resources/views/test.blade.php
<x-guest-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="flex p-4 mb-4 text-sm text-blue-700 bg-blue-100 rounded-lg dark:bg-blue-200 dark:text-blue-800" role="alert">
        <svg class="inline flex-shrink-0 mr-3 w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
        <div>
            <span class="font-medium">Info alert!</span> Change a few things up and try submitting again.
        </div>
    </div>
</x-guest-layout>