routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the 'web' middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('home');
});

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('profile', [App\Http\Controllers\UserController::class, 'showProfile'])->name('user.profile');
    Route::get('user-data', [App\Http\Controllers\UserController::class, 'getDatatables'])->name('user.data');
    Route::patch('profile', [App\Http\Controllers\UserController::class, 'updateProfile'])->name('user.update-profile');
    Route::resource('user', App\Http\Controllers\UserController::class);

    Route::get('purchase-request-data', [App\Http\Controllers\PurchaseRequestController::class, 'getDatatables'])->name('purchase-request.data');
    Route::patch('purchase-request/{purchase_request}/finalize', [App\Http\Controllers\PurchaseRequestController::class, 'finalize'])->name('purchase-request.finalize');
    Route::resource('purchase-request', App\Http\Controllers\PurchaseRequestController::class);

    Route::get('purchase-request/{purchase_request}/quotation/create', [App\Http\Controllers\QuotationController::class, 'create'])->name('purchase-request.create-quotation');
    Route::post('purchase-request/{purchase_request}/quotation/store', [App\Http\Controllers\QuotationController::class, 'store'])->name('purchase-request.store-quotation');
    Route::get('purchase-request/{purchase_request}/quotation/index', [App\Http\Controllers\QuotationController::class, 'index'])->name('purchase-request.index-quotation');
    Route::get('purchase-request/{purchase_request}/quotation/datatable', [App\Http\Controllers\QuotationController::class, 'getDatatables'])->name('purchase-request.datatable-quotation');

    Route::get('quotation/{quotation}', [App\Http\Controllers\QuotationController::class, 'show'])->name('quotation.show');
    Route::get('quotation', [App\Http\Controllers\QuotationController::class, 'index'])->name('quotation.index');
    Route::get('quotation-data', [App\Http\Controllers\QuotationController::class, 'getDatatables'])->name('quotation.data');
    Route::patch('quotation/{quotation}', [App\Http\Controllers\QuotationController::class, 'update'])->name('quotation.update');
    Route::patch('quotation/{quotation}/finalize', [App\Http\Controllers\QuotationController::class, 'finalize'])->name('quotation.finalize');

    Route::get('api-server-data', [App\Http\Controllers\ApiServerController::class, 'getDatatables'])->name('api-server.data');
    Route::resource('api-server', App\Http\Controllers\ApiServerController::class);
});
// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

app/Models/Administrator.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Administrator extends Model
{
    use HasFactory;

    public function user()
    {
        return $this->belongsTo(\App\Models\User::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Laravel\Sanctum\HasApiTokens;
use Hash;
use Storage;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'avatar_path',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function password(): Attribute
    {
        return Attribute::make(
            set: fn ($value) => Hash::make($value),
        );
    }

    public function avatarPath(): Attribute
    {
        return Attribute::make(
            get: fn ($value) => $value ? Storage::url($value) : asset('images/avatar.png'),
        );
    }

    public function roles()
    {
        return $this->belongsToMany(\App\Models\Role::class, 'role_user_pivot');
    }

    public function hasRole($name)
    {
        foreach($this->roles as $role)
        {
            if ($role->name === $name) return true;
        }

        return false;
    }

    public function scopeOfRole($query, $role)
    {
        return $query->whereHas('roles', function($query) use ($role) {
            $query->where('name', $role);
        });
    }

    public function administrator()
    {
        return $this->hasOne(\App\Models\Administrator::class);
    }

    public function client()
    {
        return $this->hasOne(\App\Models\Client::class);
    }

    public function vendor()
    {
        return $this->hasOne(\App\Models\Vendor::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Http\Requests\User\ListUserRequest;
use App\Http\Requests\User\ShowUserRequest;
use App\Http\Requests\User\IndexUserRequest;
use App\Http\Requests\User\StoreUserRequest;
use App\Http\Requests\User\CreateUserRequest;
use App\Http\Requests\User\UpdateUserRequest;
use App\Http\Requests\User\UpdateProfileRequest;

class UserController extends Controller
{
    public function index(IndexUserRequest $request)
    {
        return $request->fulfill();
    }

    public function getDatatables(ListUserRequest $request)
    {
        return $request->fulfill();
    }

    public function create(CreateUserRequest $request)
    {
        return view('user.administrator.create');
    }

    public function store(StoreUserRequest $request)
    {
        $user = $request->fulfill();

        return redirect()->route('user.index')->with('success', __('User created successfully!'));
    }

    public function show(ShowUserRequest $request, User $user)
    {
        return $request->fulfill($user);
    }

    public function update(UpdateUserRequest $request, User $user)
    {
        $request->fulfill($user);

        return redirect()->route('user.index')->with('success', __('User updated successfully!'));
    }

    public function showProfile()
    {
        $user = auth()->user();
        // $user->load('student');
        // $user->birth_date = $user->student?->birth_date;
        // $user->gender = $user->student?->gender;

        return view('user.profile')
            ->with('user', $user);
    }

    public function updateProfile(UpdateProfileRequest $request)
    {
        $user = $request->fulfill();

        return redirect()->route('user.profile')->with('success', __('Profile updated successfully!'));
    }
}

resources/views/user/administrator/create.blade.php
@extends('layouts.master')

@section('title') {{ __('User Management') }} @endsection

@section('content')

    @component('components.breadcrumb')
        @slot('li_1') <a href="{{ route('user.index') }}">{{ __('User Management') }}</a> @endslot
        @slot('title') {{ __('Create User') }} @endslot
    @endcomponent

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">

                    <x-validation-errors :errors="$errors" />

                    <h4 class="card-title mb-4">{{ __('Create New User') }}</h4>

                    <form method="post" action="{{ route('user.store') }}" enctype="multipart/form-data">
                        @csrf

                        <div class="row mb-4">
                            <label for="userName" class="col-form-label col-lg-2">{{ __('Name') }}</label>
                            <div class="col-lg-10">
                                <input id="userName" name="name" type="text" class="form-control" placeholder="Enter User Name">
                            </div>
                        </div>

                        <div class="row mb-4">
                            <label for="userEmail" class="col-form-label col-lg-2">{{ __('Email') }}</label>
                            <div class="col-lg-10">
                                <input id="userEmail" name="email" type="email" class="form-control" placeholder="Enter User Email">
                            </div>
                        </div>

                        <div class="row mb-4">
                            <label for="userPassword" class="col-form-label col-lg-2">{{ __('Password') }}</label>
                            <div class="col-lg-10">
                                <input id="userPassword" name="password" type="password" class="form-control" placeholder="Enter User Password">
                            </div>
                        </div>

                        <div class="row mb-4">
                            <label for="userPasswordConfirmation" class="col-form-label col-lg-2">{{ __('Password Confirmation') }}</label>
                            <div class="col-lg-10">
                                <input id="userPasswordConfirmation" name="password_confirmation" type="password" class="form-control" placeholder="Confirm User Password">
                            </div>
                        </div>

                        <div class="row mb-4">
                            <label for="userRole" class="col-form-label col-lg-2">{{ __('User Role') }}</label>
                            <div class="col-lg-10">
                                <select id="userRole" name="role" class="form-select">
                                    @foreach (\App\Models\Role::all() as $role)
                                        @unless ($role->name == 'client')
                                        <option value="{{ $role->id }}" @selected($role->id == old('role'))>{{ ucfirst($role->name) }}</option>
                                        @endunless
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <!-- Related attributes -->
                        <div id="dynamicProperties">
                            @include('user.administrator.attributes.create.administrator')
                            @include('user.administrator.attributes.create.client')
                            @include('user.administrator.attributes.create.vendor')
                        </div>

                        <div class="row justify-content-end">
                            <div class="col-lg-10">
                                <a href="{{ route('user.index') }}" role="button" class="btn btn-outline-secondary">{{ __('Cancel') }}</a>
                                <button type="submit" class="btn btn-primary">{{ __('Create User') }}</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div> <!-- end col -->
    </div> <!-- end row -->

@endsection

@section('script')
    <script>
    $(document).ready(function() {

        $('select#userRole').on('change', function(i) {
            var selectedRole = $(this).find(':selected').text().toLowerCase();
            var targetProperty = selectedRole + 'Properties';
            $('#dynamicProperties').children('div').each(function(i) {
                $(this).attr('hidden', true).find('input').prop('disabled', true);
            })
            $('#dynamicProperties').find('#'+targetProperty).attr('hidden', false).find('input').prop('disabled', false);
        });

        $('select#userRole').trigger('change');

        // $('[data-toggle="datepicker"]').datepicker({
        //     autoHide: true,
        //     format: 'dd/mm/yyyy',
        //     template: datepickerTemplate,
        //     itemTag: 'div',
        //     defaultItemClass: 'cursor-pointer text-center leading-none rounded-full leading-loose transition ease-in-out duration-100 hover:bg-gray-200',
        //     defaultMonthItemClass: 'cursor-pointer text-center leading-none rounded-full leading-loose transition ease-in-out duration-100 hover:bg-gray-200',
        //     defaultYearItemClass: 'cursor-pointer text-center leading-none rounded-full leading-loose transition ease-in-out duration-100 hover:bg-gray-200',
        //     highlightedClass: 'bg-light-sea-green text-white',
        //     pickedClass: 'bg-plump-purple text-white',
        //     mutedClass: 'text-gray-500',
        //     // container: "::after",
        //     offset: -45,
        //     // offset: 85,
        // });


    });
    </script>

@endsection

resources/views/user/administrator/index.blade.php
@extends('layouts.master')

@section('title') User Management @endsection

@section('css')
    <!-- DataTables -->
    <link href="{{ URL::asset('/assets/libs/datatables/datatables.min.css') }}" rel="stylesheet" type="text/css" />
@endsection

@section('content')

    @component('components.breadcrumb')
        @slot('actionButtons')
        <a href="{{ route('user.create') }}" class="btn btn-primary" role="button">
            <i class="bx bx-plus me-1"></i> Add User
        </a>
        @endslot
        @slot('li_1') Dashboard @endslot
        @slot('title') User Management @endslot
    @endcomponent

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">

                    <x-notification />

                    <!-- <h4 class="card-title">User List</h4> -->
                    <!-- <p class="card-title-desc"></p> -->

                    <table id="dataTable" class="table table-bordered dt-responsive  nowrap w-100">
                        <thead>
                            <tr>
                                <th>{{ __('Name') }}</th>
                                <th>{{ __('Email') }}</th>
                                <th>{{ __('Role') }}</th>
                                <th>{{ __('Action') }}</th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div> <!-- end col -->
    </div> <!-- end row -->

@endsection

@section('script')
    <!-- Required datatable js -->
    <script src="{{ asset('assets/libs/datatables/datatables.min.js') }}"></script>
    <script src="{{ asset('assets/libs/jszip/jszip.min.js') }}"></script>
    <script src="{{ asset('assets/libs/pdfmake/pdfmake.min.js') }}"></script>

    <script src="{{ asset('js/datatables/plugin.js') }}"></script>
    <script src="{{ asset('assets/libs/moment/moment.min.js') }}"></script>
    <script>
    $(document).ready(function() {

        var table = $('#dataTable').DataTable({
            autoWidth: false,
            // lengthChange: false,
            searching: true,
            processing: true,
            serverSide: true,
            responsive: true,
            order: [[0, "desc"]],
            ajax: {
                url: '{{ route("user.data") }}',
                error: function (jqXHR, textStatus, errorThrown) {
                    console.log(errorThrown);
                },
                statusCode: {
                    403: function() {
                        window.location.href = '{{ route("home") }}';
                    }
                }
            },
            columns: [
                { data: 'name' },
                { data: 'email' },
                {
                    data: 'roles',
                    name: 'roles.name',
                    // sortable: false,
                    render: function ( data, type, row, meta ) {
                        roles = new Array();
                        $.each(data, function(i,e) {
                            roles.push(e.name);
                        })
                        return roles.join(', ');
                    },
                },
                {
                    sortable: false,
                    data: 'id',
                    render: function ( data, type, row, meta ) {
                        // var buttonClass = "inline-flex items-center px-4 py-2 rounded-lg font-semibold text-xs uppercase tracking-widest text-white focus:outline-none bg-indigo-500 border border-indigo-500 hover:bg-indigo-400 hover:border-indigo-500 focus:z-10 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700 transition ease-in-out duration-150";
                        var buttonClass = "btn btn-primary btn-sm";
                        var targetUrl = "{{ route('user.index') }}/"+data;
                        var button = '<a href="'+targetUrl+'" class="'+buttonClass+'" data-uuid="'+data+'">View</a>';
                        return button;
                    },
                },
            ]
        });

        $(".dataTables_length select").addClass('form-select form-select-sm');

        $('#searchTable').keyup(delayResponse(function (e) {
            console.log(this.value);
            table.search( this.value ).draw();
        }, 500));

    });
    </script>

@endsection

resources/views/user/administrator/show.blade.php
@extends('layouts.master')

@section('title') {{ __('User Management') }} @endsection

@section('content')

    @component('components.breadcrumb')
        @slot('li_1') <a href="{{ route('user.index') }}">{{ __('User Management') }}</a> @endslot
        @slot('title') {{ __('Edit User') }} @endslot
    @endcomponent

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">

                    <x-validation-errors :errors="$errors" />

                    <h4 class="card-title mb-4">{{ __('User Detail') }}</h4>

                    <form method="post" action="{{ route('user.update', $user) }}" enctype="multipart/form-data">
                        @method('PATCH')
                        @csrf

                        <div class="row mb-4">
                            <label for="userName" class="col-form-label col-lg-2">{{ __('Name') }}</label>
                            <div class="col-lg-10">
                                <input id="userName" name="name" type="text" class="form-control" placeholder="Enter User Name" value="{{ old('name', $user->name) }}">
                            </div>
                        </div>

                        <div class="row mb-4">
                            <label for="userEmail" class="col-form-label col-lg-2">{{ __('Email') }}</label>
                            <div class="col-lg-10">
                                <input id="userEmail" name="email" type="email" class="form-control" placeholder="Enter User Email" value="{{ old('email', $user->email) }}">
                            </div>
                        </div>

                        <div class="row mb-4">
                            <label for="userPassword" class="col-form-label col-lg-2">{{ __('Password') }}</label>
                            <div class="col-lg-10">
                                <input id="userPassword" name="password" type="password" class="form-control" placeholder="Enter User Password">
                            </div>
                        </div>

                        <div class="row mb-4">
                            <label for="userPasswordConfirmation" class="col-form-label col-lg-2">{{ __('Password Confirmation') }}</label>
                            <div class="col-lg-10">
                                <input id="userPasswordConfirmation" name="password_confirmation" type="password" class="form-control" placeholder="Confirm User Password">
                            </div>
                        </div>

                        <!-- Avatar -->
                        <div class="row mb-4">
                            <label for="avatar" class="col-form-label col-lg-2">{{ __('Avatar') }}</label>
                            <div class="col-lg-10">
                                <a href="{{ $user->avatar_path }}" target="_blank"><img src="{{ $user->avatar_path }}" class="dashboard-avatar my-2"></a>
                                <input id="avatar" name="avatar" type="file" class="form-control" >
                            </div>
                        </div>

                        <div class="row mb-4">
                            <label for="userRole" class="col-form-label col-lg-2">{{ __('User Role') }}</label>
                            <div class="col-lg-10">
                                <select id="userRole" name="role" class="form-select">
                                    @foreach (\App\Models\Role::all() as $role)
                                    <option value="{{ $role->id }}" @selected($role->id == $user->roles()->first()->id)>{{ ucfirst($role->name) }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <!-- Related attributes -->
                        <div id="dynamicProperties">
                            @include('user.administrator.attributes.update.administrator')
                            @include('user.administrator.attributes.update.client')
                            @include('user.administrator.attributes.update.vendor')
                        </div>

                        <div class="row justify-content-end">
                            <div class="col-lg-10">
                                <a href="{{ route('user.index') }}" role="button" class="btn btn-outline-secondary">{{ __('Cancel') }}</a>
                                <button type="submit" class="btn btn-primary">{{ __('Update User') }}</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div> <!-- end col -->
    </div> <!-- end row -->

@endsection

@section('script')
    <script>
    $(document).ready(function() {

        $('select#userRole').on('change', function(i) {
            var selectedRole = $(this).find(':selected').text().toLowerCase();
            var targetProperty = selectedRole + 'Properties';
            $('#dynamicProperties').children('div').each(function(i) {
                $(this).attr('hidden', true).find('input').prop('disabled', true);
            })
            $('#dynamicProperties').find('#'+targetProperty).attr('hidden', false).find('input').prop('disabled', false);
        });

        $('select#userRole').trigger('change');

        // $('[data-toggle="datepicker"]').datepicker({
        //     autoHide: true,
        //     format: 'dd/mm/yyyy',
        //     template: datepickerTemplate,
        //     itemTag: 'div',
        //     defaultItemClass: 'cursor-pointer text-center leading-none rounded-full leading-loose transition ease-in-out duration-100 hover:bg-gray-200',
        //     defaultMonthItemClass: 'cursor-pointer text-center leading-none rounded-full leading-loose transition ease-in-out duration-100 hover:bg-gray-200',
        //     defaultYearItemClass: 'cursor-pointer text-center leading-none rounded-full leading-loose transition ease-in-out duration-100 hover:bg-gray-200',
        //     highlightedClass: 'bg-light-sea-green text-white',
        //     pickedClass: 'bg-plump-purple text-white',
        //     mutedClass: 'text-gray-500',
        //     // container: "::after",
        //     offset: -45,
        //     // offset: 85,
        // });


    });
    </script>

@endsection