routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the 'web' middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('home');
});

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('profile', [App\Http\Controllers\UserController::class, 'showProfile'])->name('user.profile');
    Route::get('user-data', [App\Http\Controllers\UserController::class, 'getDatatables'])->name('user.data');
    Route::patch('profile', [App\Http\Controllers\UserController::class, 'updateProfile'])->name('user.update-profile');
    Route::resource('user', App\Http\Controllers\UserController::class);

    Route::get('purchase-request-data', [App\Http\Controllers\PurchaseRequestController::class, 'getDatatables'])->name('purchase-request.data');
    Route::patch('purchase-request/{purchase_request}/finalize', [App\Http\Controllers\PurchaseRequestController::class, 'finalize'])->name('purchase-request.finalize');
    Route::resource('purchase-request', App\Http\Controllers\PurchaseRequestController::class);

    Route::get('purchase-request/{purchase_request}/quotation/create', [App\Http\Controllers\QuotationController::class, 'create'])->name('purchase-request.create-quotation');
    Route::post('purchase-request/{purchase_request}/quotation/store', [App\Http\Controllers\QuotationController::class, 'store'])->name('purchase-request.store-quotation');
    Route::get('purchase-request/{purchase_request}/quotation/index', [App\Http\Controllers\QuotationController::class, 'index'])->name('purchase-request.index-quotation');
    Route::get('purchase-request/{purchase_request}/quotation/datatable', [App\Http\Controllers\QuotationController::class, 'getDatatables'])->name('purchase-request.datatable-quotation');

    Route::get('quotation/{quotation}', [App\Http\Controllers\QuotationController::class, 'show'])->name('quotation.show');
    Route::get('quotation', [App\Http\Controllers\QuotationController::class, 'index'])->name('quotation.index');
    Route::get('quotation-data', [App\Http\Controllers\QuotationController::class, 'getDatatables'])->name('quotation.data');
    Route::patch('quotation/{quotation}', [App\Http\Controllers\QuotationController::class, 'update'])->name('quotation.update');
    Route::patch('quotation/{quotation}/finalize', [App\Http\Controllers\QuotationController::class, 'finalize'])->name('quotation.finalize');

    Route::get('api-server-data', [App\Http\Controllers\ApiServerController::class, 'getDatatables'])->name('api-server.data');
    Route::resource('api-server', App\Http\Controllers\ApiServerController::class);
});
// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

app/Models/Administrator.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Administrator extends Model
{
    use HasFactory;

    public function user()
    {
        return $this->belongsTo(\App\Models\User::class);
    }
}

app/Models/ApiServer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ApiServer extends Model
{
    use HasFactory;

    protected $guarded = ['id'];
    
}

app/Http/Controllers/ApiServerController.php
<?php

namespace App\Http\Controllers;

use App\Models\ApiServer;
use App\Http\Requests\ApiServer\ListApiServerRequest;
use App\Http\Requests\ApiServer\ShowApiServerRequest;
use App\Http\Requests\ApiServer\IndexApiServerRequest;
use App\Http\Requests\ApiServer\StoreApiServerRequest;
use App\Http\Requests\ApiServer\CreateApiServerRequest;
use App\Http\Requests\ApiServer\UpdateApiServerRequest;
use App\Http\Requests\ApiServer\DestroyApiServerRequest;

class ApiServerController extends Controller
{
    public function index(IndexApiServerRequest $request)
    {
        return $request->fulfill();
    }

    public function getDatatables(ListApiServerRequest $request)
    {
        return $request->fulfill();
    }

    public function create(CreateApiServerRequest $request)
    {
        return view('api-server.administrator.create');
    }

    public function store(StoreApiServerRequest $request)
    {
        $user = $request->fulfill();

        return redirect()->route('api-server.index');
    }

    public function show(ShowApiServerRequest $request, ApiServer $apiServer)
    {
        return $request->fulfill($apiServer);
    }

    public function update(UpdateApiServerRequest $request, ApiServer $apiServer)
    {
        $request->fulfill($apiServer);

        return redirect()->route('api-server.index');
    }

    public function destroy(DestroyApiServerRequest $request, ApiServer $apiServer)
    {
        $request->fulfill($apiServer);

        return redirect()->route('api-server.index');
    }
}

resources/views/api-server/administrator/create.blade.php
@extends('layouts.master')

@section('title') {{ __('Api Server Management') }} @endsection

@section('content')

    @component('components.breadcrumb')
        @slot('li_1') <a href="{{ route('api-server.index') }}">{{ __('Api Server Management') }}</a> @endslot
        @slot('title') {{ __('Create Api Server') }} @endslot
    @endcomponent

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">

                    <x-validation-errors :errors="$errors" />

                    <h4 class="card-title mb-4">{{ __('Create New Api Server') }}</h4>

                    <form method="post" action="{{ route('api-server.store') }}" enctype="multipart/form-data">
                        @csrf

                        <div class="row mb-4">
                            <label for="apiServerName" class="col-form-label col-lg-2">{{ __('Name') }}</label>
                            <div class="col-lg-10">
                                <input id="apiServerName" name="name" type="text" class="form-control" placeholder="Enter Api Server Name">
                            </div>
                        </div>

                        <div class="row mb-4">
                            <label for="apiServerBaseUri" class="col-form-label col-lg-2">{{ __('Base URI') }}</label>
                            <div class="col-lg-10">
                                <input id="apiServerBaseUri" name="base_uri" type="text" class="form-control" placeholder="Enter Api Server Base URI">
                            </div>
                        </div>

                        <div class="row mb-4">
                            <label for="apiServerUserName" class="col-form-label col-lg-2">{{ __('Username') }}</label>
                            <div class="col-lg-10">
                                <input id="apiServerUserName" name="username" type="text" class="form-control" placeholder="Enter Api Server Username">
                            </div>
                        </div>

                        <div class="row mb-4">
                            <label for="apiServerPassword" class="col-form-label col-lg-2">{{ __('Password') }}</label>
                            <div class="col-lg-10">
                                <input id="apiServerPassword" name="password" type="text" class="form-control" placeholder="Enter Api Server Password">
                            </div>
                        </div>

                        <div class="row justify-content-end">
                            <div class="col-lg-10">
                                <a href="{{ route('api-server.index') }}" role="button" class="btn btn-outline-secondary">Cancel</a>
                                <button type="submit" class="btn btn-primary">Create Api Server</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div> <!-- end col -->
    </div> <!-- end row -->

@endsection

@section('script')
    <script>
    $(document).ready(function() {

    });
    </script>

@endsection

resources/views/api-server/administrator/index.blade.php
@extends('layouts.master')

@section('title') Api Server Management @endsection

@section('css')
    <!-- DataTables -->
    <link href="{{ URL::asset('/assets/libs/datatables/datatables.min.css') }}" rel="stylesheet" type="text/css" />
@endsection

@section('content')

    @component('components.breadcrumb')
        @slot('actionButtons')
        <a href="{{ route('api-server.create') }}" class="btn btn-primary" role="button">
            <i class="bx bx-plus me-1"></i> Add Api Server
        </a>
        @endslot
        @slot('li_1') Dashboard @endslot
        @slot('title') Api Server Management @endslot
    @endcomponent

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">

                    <!-- <h4 class="card-title">Api Server List</h4> -->
                    <!-- <p class="card-title-desc"></p> -->

                    <table id="dataTable" class="table table-bordered dt-responsive  nowrap w-100">
                        <thead>
                            <tr>
                                <th>{{ __('Name') }}</th>
                                <th>{{ __('Base URI') }}</th>
                                <th>{{ __('Username') }}</th>
                                <th>{{ __('Password') }}</th>
                                <th>{{ __('Action') }}</th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div> <!-- end col -->
    </div> <!-- end row -->

@endsection

@section('script')
    <!-- Required datatable js -->
    <script src="{{ asset('assets/libs/datatables/datatables.min.js') }}"></script>
    <script src="{{ asset('assets/libs/jszip/jszip.min.js') }}"></script>
    <script src="{{ asset('assets/libs/pdfmake/pdfmake.min.js') }}"></script>

    <script src="{{ asset('js/datatables/plugin.js') }}"></script>
    <script src="{{ asset('assets/libs/moment/moment.min.js') }}"></script>
    <script>
    $(document).ready(function() {

        var table = $('#dataTable').DataTable({
            autoWidth: false,
            // lengthChange: false,
            searching: true,
            processing: true,
            serverSide: true,
            responsive: true,
            order: [[0, "desc"]],
            ajax: {
                url: '{{ route("api-server.data") }}',
                error: function (jqXHR, textStatus, errorThrown) {
                    console.log(errorThrown);
                },
                statusCode: {
                    403: function() {
                        window.location.href = '{{ route("home") }}';
                    }
                }
            },
            columns: [
                { data: 'name' },
                { data: 'base_uri' },
                { data: 'username' },
                { data: 'password' },
                {
                    sortable: false,
                    data: 'id',
                    render: function ( data, type, row, meta ) {
                        // var buttonClass = "inline-flex items-center px-4 py-2 rounded-lg font-semibold text-xs uppercase tracking-widest text-white focus:outline-none bg-indigo-500 border border-indigo-500 hover:bg-indigo-400 hover:border-indigo-500 focus:z-10 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700 transition ease-in-out duration-150";
                        var buttonClass = "btn btn-primary btn-sm";
                        var targetUrl = "{{ route('api-server.index') }}/"+data;
                        var button = '<a href="'+targetUrl+'" class="'+buttonClass+'" data-uuid="'+data+'">View</a>';
                        return button;
                    },
                },
            ]
        });

        $(".dataTables_length select").addClass('form-select form-select-sm');

        $('#searchTable').keyup(delayResponse(function (e) {
            console.log(this.value);
            table.search( this.value ).draw();
        }, 500));

    });
    </script>

@endsection

resources/views/api-server/administrator/show.blade.php
@extends('layouts.master')

@section('title') {{ __('Api Server Management') }} @endsection

@section('content')

    @component('components.breadcrumb')
        @slot('actionButtons')
            @can('delete', $api_server)
            <form method="post" action="{{ route('api-server.destroy', $api_server) }}">
                @method('DELETE')
                @csrf
                <button class="btn btn-danger" type="submit">
                    <i class="bx bx-trash me-1"></i> {{ __('Delete') }}
                </button>
            </form>
            @endcan
        @endslot
        @slot('li_1') <a href="{{ route('api-server.index') }}">{{ __('Api Server Management') }}</a> @endslot
        @slot('title') {{ __('Edit Api Server') }} @endslot
    @endcomponent

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">

                    <x-validation-errors :errors="$errors" />

                    <h4 class="card-title mb-4">{{ __('Api Server Detail') }}</h4>

                    <form method="post" action="{{ route('api-server.update', $api_server) }}" enctype="multipart/form-data">
                        @method('PATCH')
                        @csrf

                        <div class="row mb-4">
                            <label for="apiServerName" class="col-form-label col-lg-2">{{ __('Name') }}</label>
                            <div class="col-lg-10">
                                <input id="apiServerName" name="name" type="text" class="form-control" placeholder="Enter Api Server Name" value="{{ old('name', $api_server->name) }}">
                            </div>
                        </div>

                        <div class="row mb-4">
                            <label for="apiServerBaseUri" class="col-form-label col-lg-2">{{ __('Base URI') }}</label>
                            <div class="col-lg-10">
                                <input id="apiServerBaseUri" name="base_uri" type="text" class="form-control" placeholder="Enter Api Server Base URI" value="{{ old('base_uri', $api_server->base_uri) }}">
                            </div>
                        </div>

                        <div class="row mb-4">
                            <label for="apiServerUserName" class="col-form-label col-lg-2">{{ __('Username') }}</label>
                            <div class="col-lg-10">
                                <input id="apiServerUserName" name="username" type="text" class="form-control" placeholder="Enter Api Server Username" value="{{ old('username', $api_server->username) }}">
                            </div>
                        </div>

                        <div class="row mb-4">
                            <label for="apiServerPassword" class="col-form-label col-lg-2">{{ __('Password') }}</label>
                            <div class="col-lg-10">
                                <input id="apiServerPassword" name="password" type="text" class="form-control" placeholder="Enter Api Server Password" value="{{ old('password', $api_server->password) }}">
                            </div>
                        </div>

                        <div class="row justify-content-end">
                            <div class="col-lg-10">
                                <a href="{{ route('api-server.index') }}" role="button" class="btn btn-outline-secondary">{{ __('Cancel') }}</a>
                                <button type="submit" class="btn btn-primary">{{ __('Update Api Server') }}</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div> <!-- end col -->
    </div> <!-- end row -->

@endsection

@section('script')
    <script>
    $(document).ready(function() {

    });
    </script>

@endsection